/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as BrandIndexRouteImport } from './routes/brand/index'
import { Route as BrandTestRouteImport } from './routes/brand/test'
import { Route as BrandLayoutRouteImport } from './routes/brand/_layout'
import { Route as BrandLayoutWhitepowderIndexRouteImport } from './routes/brand/_layout/whitepowder/index'
import { Route as BrandLayoutSpriteIndexRouteImport } from './routes/brand/_layout/sprite/index'
import { Route as BrandLayoutFengIndexRouteImport } from './routes/brand/_layout/feng/index'

const BrandRouteImport = createFileRoute('/brand')()

const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandRoute,
} as any)
const BrandTestRoute = BrandTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => BrandRoute,
} as any)
const BrandLayoutRoute = BrandLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => BrandRoute,
} as any)
const BrandLayoutWhitepowderIndexRoute =
  BrandLayoutWhitepowderIndexRouteImport.update({
    id: '/whitepowder/',
    path: '/whitepowder/',
    getParentRoute: () => BrandLayoutRoute,
  } as any)
const BrandLayoutSpriteIndexRoute = BrandLayoutSpriteIndexRouteImport.update({
  id: '/sprite/',
  path: '/sprite/',
  getParentRoute: () => BrandLayoutRoute,
} as any)
const BrandLayoutFengIndexRoute = BrandLayoutFengIndexRouteImport.update({
  id: '/feng/',
  path: '/feng/',
  getParentRoute: () => BrandLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandLayoutRouteWithChildren
  '/brand/test': typeof BrandTestRoute
  '/brand/': typeof BrandIndexRoute
  '/test': typeof TestIndexRoute
  '/brand/feng': typeof BrandLayoutFengIndexRoute
  '/brand/sprite': typeof BrandLayoutSpriteIndexRoute
  '/brand/whitepowder': typeof BrandLayoutWhitepowderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandIndexRoute
  '/brand/test': typeof BrandTestRoute
  '/test': typeof TestIndexRoute
  '/brand/feng': typeof BrandLayoutFengIndexRoute
  '/brand/sprite': typeof BrandLayoutSpriteIndexRoute
  '/brand/whitepowder': typeof BrandLayoutWhitepowderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRouteWithChildren
  '/brand/_layout': typeof BrandLayoutRouteWithChildren
  '/brand/test': typeof BrandTestRoute
  '/brand/': typeof BrandIndexRoute
  '/test/': typeof TestIndexRoute
  '/brand/_layout/feng/': typeof BrandLayoutFengIndexRoute
  '/brand/_layout/sprite/': typeof BrandLayoutSpriteIndexRoute
  '/brand/_layout/whitepowder/': typeof BrandLayoutWhitepowderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/brand/test'
    | '/brand/'
    | '/test'
    | '/brand/feng'
    | '/brand/sprite'
    | '/brand/whitepowder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/brand/test'
    | '/test'
    | '/brand/feng'
    | '/brand/sprite'
    | '/brand/whitepowder'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/brand/_layout'
    | '/brand/test'
    | '/brand/'
    | '/test/'
    | '/brand/_layout/feng/'
    | '/brand/_layout/sprite/'
    | '/brand/_layout/whitepowder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRouteWithChildren
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/': {
      id: '/brand/'
      path: '/'
      fullPath: '/brand/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/test': {
      id: '/brand/test'
      path: '/test'
      fullPath: '/brand/test'
      preLoaderRoute: typeof BrandTestRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/_layout': {
      id: '/brand/_layout'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandLayoutRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/_layout/whitepowder/': {
      id: '/brand/_layout/whitepowder/'
      path: '/whitepowder'
      fullPath: '/brand/whitepowder'
      preLoaderRoute: typeof BrandLayoutWhitepowderIndexRouteImport
      parentRoute: typeof BrandLayoutRoute
    }
    '/brand/_layout/sprite/': {
      id: '/brand/_layout/sprite/'
      path: '/sprite'
      fullPath: '/brand/sprite'
      preLoaderRoute: typeof BrandLayoutSpriteIndexRouteImport
      parentRoute: typeof BrandLayoutRoute
    }
    '/brand/_layout/feng/': {
      id: '/brand/_layout/feng/'
      path: '/feng'
      fullPath: '/brand/feng'
      preLoaderRoute: typeof BrandLayoutFengIndexRouteImport
      parentRoute: typeof BrandLayoutRoute
    }
  }
}

interface BrandLayoutRouteChildren {
  BrandLayoutFengIndexRoute: typeof BrandLayoutFengIndexRoute
  BrandLayoutSpriteIndexRoute: typeof BrandLayoutSpriteIndexRoute
  BrandLayoutWhitepowderIndexRoute: typeof BrandLayoutWhitepowderIndexRoute
}

const BrandLayoutRouteChildren: BrandLayoutRouteChildren = {
  BrandLayoutFengIndexRoute: BrandLayoutFengIndexRoute,
  BrandLayoutSpriteIndexRoute: BrandLayoutSpriteIndexRoute,
  BrandLayoutWhitepowderIndexRoute: BrandLayoutWhitepowderIndexRoute,
}

const BrandLayoutRouteWithChildren = BrandLayoutRoute._addFileChildren(
  BrandLayoutRouteChildren,
)

interface BrandRouteChildren {
  BrandLayoutRoute: typeof BrandLayoutRouteWithChildren
  BrandTestRoute: typeof BrandTestRoute
  BrandIndexRoute: typeof BrandIndexRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandLayoutRoute: BrandLayoutRouteWithChildren,
  BrandTestRoute: BrandTestRoute,
  BrandIndexRoute: BrandIndexRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRouteWithChildren,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
